pipeline {
    agent { docker { image 'maven:3.9.5-eclipse-temurin-17-alpine' } }
    options {
        ansiColor('xterm')
    }
    // stages {
    //     stage('Build') {
    //         steps {
    //             sh 'mvn -B -DskipTests clean package'
    //         }
    //     }
    //     stage('Test') {
    //         steps {
    //             sh 'mvn test'
    //         }
    //         post {
    //             always {
    //                 junit 'target/surefire-reports/*.xml'
    //             }
    //         }
    //     }
    //     stage('Deliver') {
    //         steps {
    //             sh './jenkins/scripts/deliver.sh'
    //         }
    //     }
    //     stage('Complete') {
    //         steps {
    //             echo "Job complete"
    //         }
    //     }
    // }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}
